require 'spec_helper'

describe "Users" do
  
  describe "signup" do
    
    
    	    
################ TEST THAT SIGNUP FAILURE DOESN'T PRODUCE USER CEREATION IN DB ###########
    
    describe "failure" do      

        it "should not make a new user" do
      	      # we need to wrap the test steps in a single package, and then check that it doesn’t change the User count. 
      	      # this can be accomplished with a lambda. 
      	      # lambda block can wrap multiple lines
      	      lambda do
        visit signup_path
        fill_in "Name",         :with => ""
        fill_in "Email",        :with => ""
        fill_in "Password",     :with => ""
        fill_in "Confirmation", :with => ""
        click_button
        response.should render_template('users/new')
        response.should have_selector("div#error_explanation")
              end.should_not change(User, :count)
      end
    end
    
    # Here the first arguments to fill_in are the label values, i.e., exactly the text the user sees in the browser; 
    # there’s no need to know anything about the underlying HTML structure generated by the Rails form_for helper.
    
################ TEST FOR SIGNUP SUCCESS ##################

    describe "success" do

         it "should make a new user" do
                 lambda do
          visit signup_path
          fill_in "Name",         :with => "Example User"
          fill_in "Email",        :with => "user@example.com"
          fill_in "Password",     :with => "foobar"
          fill_in "Confirmation", :with => "foobar"
          click_button
          response.should have_selector("div.flash.success",
                                        :content => "Welcome")
          response.should render_template('users/show')
                 end.should change(User, :count).by(1)
      end
    end
    
# By the way, although it’s not obvious from the RSpec documentation, you can use the CSS id 
# of the text box instead of the label, so fill_in :user_name also works.11 
# (This is especially nice for forms that don’t use labels.)
    
    
###########################################################   
    
  end
end

